// CommonJS seed file — run with: node prisma/seed.cjs
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const cars = [
  {
    id: "hyundai-creta-2021",
    brand: "Hyundai",
    model: "Creta SX",
    variant: "",
    year: 2021,
    price: 1249000,
    mileage: 28500,
    fuel: "Petrol",
    transmission: "Automatic",
    location: "Bengaluru",
    category: "SUV",
    ownership: "1st",
    trending: true,
    featured: true,
    newArrival: false,
    verified: true,
    finance: true,
    description: "Single-owner compact SUV with a clean service history, premium cabin, touchscreen infotainment, and city-friendly automatic transmission.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1549924231-f129b911e442?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["Sunroof", "Rear camera", "Cruise control", "Apple CarPlay", "6 airbags"]),
  },
  {
    id: "maruti-baleno-2022",
    brand: "Maruti Suzuki",
    model: "Baleno Zeta",
    variant: "",
    year: 2022,
    price: 749000,
    mileage: 18200,
    fuel: "Petrol",
    transmission: "Manual",
    location: "Pune",
    category: "Hatchback",
    ownership: "1st",
    trending: false,
    featured: true,
    newArrival: true,
    verified: true,
    finance: true,
    description: "A light, efficient hatchback with low running costs and a roomy cabin for everyday family use.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["Touchscreen", "ABS", "Keyless entry", "Projector lamps", "Alloy wheels"]),
  },
  {
    id: "honda-city-2020",
    brand: "Honda",
    model: "City VX",
    variant: "",
    year: 2020,
    price: 1049000,
    mileage: 34200,
    fuel: "Petrol",
    transmission: "Manual",
    location: "Delhi NCR",
    category: "Sedan",
    ownership: "2nd",
    trending: false,
    featured: true,
    newArrival: false,
    verified: true,
    finance: false,
    description: "Elegant sedan with refined ride quality, generous rear-seat space, and dependable Honda ownership.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["Lane watch", "Climate control", "Rear AC", "LED lamps", "Push start"]),
  },
  {
    id: "kia-seltos-2023",
    brand: "Kia",
    model: "Seltos HTX",
    variant: "",
    year: 2023,
    price: 1599000,
    mileage: 12400,
    fuel: "Diesel",
    transmission: "Automatic",
    location: "Mumbai",
    category: "SUV",
    ownership: "1st",
    trending: true,
    featured: true,
    newArrival: true,
    verified: true,
    finance: true,
    description: "Feature-rich diesel automatic SUV with a planted highway feel and premium connected-car experience.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1549924231-f129b911e442?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["Ventilated seats", "Bose audio", "360 camera", "Connected tech", "TPMS"]),
  },
  {
    id: "toyota-innova-2019",
    brand: "Toyota",
    model: "Innova Crysta",
    variant: "",
    year: 2019,
    price: 1749000,
    mileage: 51500,
    fuel: "Diesel",
    transmission: "Manual",
    location: "Hyderabad",
    category: "Luxury",
    ownership: "2nd",
    trending: false,
    featured: false,
    newArrival: false,
    verified: true,
    finance: true,
    description: "Reliable seven-seater with excellent long-distance comfort and the durability buyers expect from Toyota.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["Captain seats", "Rear camera", "Dual AC", "Service records", "7 seater"]),
  },
  {
    id: "tata-nexon-2021",
    brand: "Tata",
    model: "Nexon XZ Plus",
    variant: "",
    year: 2021,
    price: 899000,
    mileage: 26800,
    fuel: "Petrol",
    transmission: "Manual",
    location: "Chennai",
    category: "Budget",
    ownership: "1st",
    trending: false,
    featured: false,
    newArrival: false,
    verified: true,
    finance: true,
    description: "A strong, safe compact SUV with bold styling, high ground clearance, and practical daily usability.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["5-star safety", "Drive modes", "Touchscreen", "Rear AC", "Hill hold"]),
  },
  {
    id: "mahindra-thar-2022",
    brand: "Mahindra",
    model: "Thar LX",
    variant: "",
    year: 2022,
    price: 1699000,
    mileage: 21000,
    fuel: "Diesel",
    transmission: "Automatic",
    location: "Jaipur",
    category: "SUV",
    ownership: "1st",
    trending: true,
    featured: false,
    newArrival: true,
    verified: true,
    finance: true,
    description: "Iconic off-roader with commanding presence, 4WD capability, and a modern premium interior suited for adventure seekers.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["4WD", "Soft top", "Touchscreen", "Cruise control", "Traction control"]),
  },
  {
    id: "volkswagen-polo-2020",
    brand: "Volkswagen",
    model: "Polo Highline Plus",
    variant: "",
    year: 2020,
    price: 789000,
    mileage: 39500,
    fuel: "Petrol",
    transmission: "Manual",
    location: "Kolkata",
    category: "Hatchback",
    ownership: "2nd",
    trending: true,
    featured: false,
    newArrival: false,
    verified: true,
    finance: false,
    description: "European build quality in a compact package. Sporty handling, solid interiors, and a loyal fan base across Indian cities.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1541443131876-44b03de101c5?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["ABS + EBD", "Touchscreen", "Climate control", "Rear defogger", "Alloy wheels"]),
  },
  {
    id: "hyundai-verna-2023",
    brand: "Hyundai",
    model: "Verna SX(O)",
    variant: "",
    year: 2023,
    price: 1349000,
    mileage: 8700,
    fuel: "Petrol",
    transmission: "Automatic",
    location: "Ahmedabad",
    category: "Sedan",
    ownership: "1st",
    trending: false,
    featured: false,
    newArrival: true,
    verified: true,
    finance: true,
    description: "Nearly new flagship sedan with panoramic sunroof, ADAS safety suite, and a dual curved display that rivals luxury competition.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1549924231-f129b911e442?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["ADAS", "Panoramic sunroof", "Ventilated seats", "Wireless charger", "Bose sound"]),
  },
  {
    id: "mg-hector-2021",
    brand: "MG",
    model: "Hector Sharp",
    variant: "",
    year: 2021,
    price: 1399000,
    mileage: 31200,
    fuel: "Petrol",
    transmission: "Manual",
    location: "Surat",
    category: "SUV",
    ownership: "2nd",
    trending: false,
    featured: false,
    newArrival: false,
    verified: false,
    finance: true,
    description: "Internet car with a commanding 10.4-inch portrait screen, premium cabin space, and connected tech rarely seen at this price.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(['10.4" screen', "Panoramic roof", "Wi-Fi", "6 airbags", "7 seater option"]),
  },
  {
    id: "renault-kwid-2021",
    brand: "Renault",
    model: "Kwid RXL",
    variant: "",
    year: 2021,
    price: 389000,
    mileage: 22100,
    fuel: "Petrol",
    transmission: "Manual",
    location: "Nagpur",
    category: "Budget",
    ownership: "1st",
    trending: false,
    featured: false,
    newArrival: false,
    verified: true,
    finance: true,
    description: "Ultra-affordable city car with SUV-inspired styling, high ground clearance, and impressive fuel economy for tight budgets.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541443131876-44b03de101c5?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["7-inch touchscreen", "High ground clearance", "Central locking", "Power windows", "ABS"]),
  },
  {
    id: "bmw-3series-2020",
    brand: "BMW",
    model: "3 Series 330i",
    variant: "",
    year: 2020,
    price: 3499000,
    mileage: 44800,
    fuel: "Petrol",
    transmission: "Automatic",
    location: "Mumbai",
    category: "Luxury",
    ownership: "2nd",
    trending: true,
    featured: false,
    newArrival: false,
    verified: true,
    finance: true,
    description: "Benchmark sports sedan with rear-wheel drive, turbocharged power, and a cabin that feels like a premium lounge at every speed.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["Leather seats", "Head-up display", "Harman Kardon", "Parking assist", "M Sport kit"]),
  },
  {
    id: "maruti-alto-2012",
    brand: "Maruti Suzuki",
    model: "Alto K10",
    variant: "",
    year: 2012,
    price: 145000,
    mileage: 44000,
    fuel: "Petrol",
    transmission: "Manual",
    location: "Lucknow",
    category: "Budget",
    ownership: "1st",
    trending: true,
    featured: false,
    newArrival: false,
    verified: true,
    finance: true,
    description: "Well-maintained first-owner city runabout with low mileage, excellent fuel efficiency, and zero major repairs in its history.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1541443131876-44b03de101c5?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["Central locking", "Power windows", "CD player", "ABS", "Good AC"]),
  },
  {
    id: "honda-jazz-2016",
    brand: "Honda",
    model: "Jazz VX",
    variant: "",
    year: 2016,
    price: 335000,
    mileage: 80000,
    fuel: "Petrol",
    transmission: "Manual",
    location: "Bengaluru",
    category: "Hatchback",
    ownership: "1st",
    trending: true,
    featured: false,
    newArrival: false,
    verified: true,
    finance: true,
    description: "Single-owner premium hatchback with Honda's legendary Magic Seat, touchscreen, and outstanding versatility for daily use.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["Magic Seat", "Touchscreen", "Reverse camera", "Climate control", "Alloy wheels"]),
  },
  {
    id: "hyundai-santro-2011",
    brand: "Hyundai",
    model: "Santro Xing",
    variant: "",
    year: 2011,
    price: 125000,
    mileage: 100000,
    fuel: "Petrol",
    transmission: "Manual",
    location: "Delhi NCR",
    category: "Budget",
    ownership: "2nd",
    trending: false,
    featured: false,
    newArrival: false,
    verified: true,
    finance: false,
    description: "Dependable tall-boy hatchback known for city agility and ease of maintenance. A practical choice for a first car or second family vehicle.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541443131876-44b03de101c5?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["Power steering", "Central locking", "AC", "Good ground clearance", "Easy to park"]),
  },
  {
    id: "ford-ecosport-2014",
    brand: "Ford",
    model: "EcoSport Titanium",
    variant: "",
    year: 2014,
    price: 290000,
    mileage: 90000,
    fuel: "Diesel",
    transmission: "Manual",
    location: "Pune",
    category: "SUV",
    ownership: "2nd",
    trending: false,
    featured: false,
    newArrival: false,
    verified: true,
    finance: true,
    description: "Frugal diesel compact SUV with generous road presence, roof-mounted spare wheel, and solid build quality from the Ford stable.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["Rear camera", "Touchscreen", "Ford SYNC", "Diesel efficiency", "High ground clearance"]),
  },
  {
    id: "hyundai-verna-2012",
    brand: "Hyundai",
    model: "Verna Transform",
    variant: "",
    year: 2012,
    price: 250000,
    mileage: 85000,
    fuel: "Petrol",
    transmission: "Manual",
    location: "Chandigarh",
    category: "Sedan",
    ownership: "2nd",
    trending: false,
    featured: false,
    newArrival: false,
    verified: true,
    finance: false,
    description: "Stylish fluidic-design sedan with a comfortable cabin and Hyundai's reputation for affordable long-term ownership.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1549924231-f129b911e442?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["Climate control", "6-speaker audio", "Rear AC vents", "Power mirrors", "Fog lamps"]),
  },
  {
    id: "volkswagen-polo-2016",
    brand: "Volkswagen",
    model: "Polo Comfortline",
    variant: "",
    year: 2016,
    price: 300000,
    mileage: 87000,
    fuel: "Diesel",
    transmission: "Manual",
    location: "Mumbai",
    category: "Hatchback",
    ownership: "1st",
    trending: false,
    featured: false,
    newArrival: false,
    verified: true,
    finance: false,
    description: "First-owner diesel Polo with exceptional fuel economy and the renowned VW build quality that holds up beautifully over the years.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1541443131876-44b03de101c5?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["1.5 TDI", "ABS", "Climate control", "Alloy wheels", "Dual airbags"]),
  },
  {
    id: "maruti-ciaz-2016",
    brand: "Maruti Suzuki",
    model: "Ciaz Alpha",
    variant: "",
    year: 2016,
    price: 420000,
    mileage: 90000,
    fuel: "Diesel",
    transmission: "Manual",
    location: "Hyderabad",
    category: "Sedan",
    ownership: "1st",
    trending: false,
    featured: false,
    newArrival: false,
    verified: true,
    finance: true,
    description: "Roomy premium diesel sedan with best-in-class rear legroom, frugal engine, and a fully-loaded cabin at a compelling price point.",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?q=80&w=1400&auto=format&fit=crop",
    ]),
    features: JSON.stringify(["Sunroof", "Rear camera", "Climate control", "Push start", "6 airbags"]),
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  // Upsert all cars
  for (const car of cars) {
    await prisma.car.upsert({
      where: { id: car.id },
      update: car,
      create: car,
    });
  }
  console.log(`✅ ${cars.length} cars seeded`);

  // Upsert admin user
  await prisma.user.upsert({
    where: { username: "admin" },
    update: { password: "cars123", role: "admin" },
    create: { username: "admin", password: "cars123", role: "admin" },
  });
  console.log("✅ Admin user seeded (username: admin, password: cars123)");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
